name: wrangle_act_environment
channels:
dependencies:
   - pandas
   - numpy
   - requests
   - notebook
   - pip:
     - "--editable=git+https://github.com/tweepy/tweepy.git@2efe385fc69385b57733f747ee62e6be12a1338b#egg=tweepy-master"